server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment route #路由的ID没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   # 匹配提供服务的路由地址
          uri: lb://cloud-payment-service   # 匹配提供服务的路由地址
          predicates:
#            2020-04-19T18:23:00.637+08:00[Asia/Shanghai]
            - Path=/payment/lb/**       #断言：路径相匹配的进行路由
            #时间级别
            #- After=2020-04-19T18:30:00.637+08:00[Asia/Shanghai]  #在时间之后
            #- Before=2020-03-19T18:30:00.637+08:00[Asia/Shanghai] #在时间之前
            #- Between=2020-04-08T10:59:34.102+08:00[Asia/Shanghai] ,  2020-04-11T10:59:34.102+08:00[Asia/Shanghai] #设置之间
            #- Cookie=username,zzyy
            #- Header=X-Request-Id,\d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Host=**.wkjy.com #-H 里 host:**.wkjy.com  curl http://localhost:9527/payment/lb -H "Host:ssss.wkjy.com"
            #- Method=POST #请求为POST curl http://localhost:9527/payment/lb -X POST
            #- Query=username,\d*  #要有参数名username并且值为正整数才能路由
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service   # 匹配提供服务的路由地址
          predicates:
            - Path=/payment/selectAll/**


eureka:
  instance:
    #注册进微服务的名称
    #hostname: cloud-gateway-service
    instance-id: gateway9527
    #prefer-ip-address: true #显示ip地址
  client:
    #注册进erueka服务
    register-with-eureka: true
    #集群需要设置成true,配合robbin使用
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
