#服务端口号
server:
  port: 8001

#服务名称
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wkjy.springcloud.entity
eureka:
  client:
    #表示是否将自己注册到eureka server  默认为true
    register-with-eureka: true
    #是否从eureka server抓取已有的注册信息，默认为true,单节点无所谓，集群必须设置为true，才能配合rabbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone:  http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #,http://eureka7003.com:7003/eureka
      defaultZone:  http://eureka7001.com:7001/eureka  #,http://eureka7002.com:7002/eureka #,http://eureka7003.com:7003/eureka
  instance: #将原来的  主机名称：服务名称  修改成 payment8001
    instance-id: payment8001
    #访问可以显示IP地址
    prefer-ip-address: true
    #hostname: sesepay

    #心跳检测和续约时间
    #开发时设置小一些，保证服务关闭后注册中心能及时剔除服务
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30）
#    lease-renewal-interval-in-seconds: 1
#    #Eureka服务端在收到最后一次心跳的上限，默认90，超时将剔除
#    lease-expiration-duration-in-seconds: 10


