server:
  port: 80
eureka:
  client:
    #注册到eureka   true：注册    false:不注册
    register-with-eureka: false
    service-url:
      defaultZone : http://eureka7001.com:7001/eureka/


#设置Feign客户端超时时间（OpenFegin默认支持Robbin）
ribbon:
  #指的是建立连接所需要的时间，适用于网络正常的情况下，两端连接所需要的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间（默认为1秒）
  ConnectTimeout: 5000

logging:
  level:
    com.wkjy.springcloud.service.PaymentFeignService: debug
