server:
  port: 7001
eureka:
  instance:
    hostname: erueka7001.com #eureka服务端的实例名称


  client:
    #false代表不向服务中心注册自己
    register-with-eureka: false
    #false表示自己就是服务端的注册中心，我的职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone:
    service-url:
      #单机版
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

      #集群版
     # defaultZone:  http://eureka7002.com:7002/eureka/  #,http://eureka7003.com:7003/eureka/
#  server:
#    #关闭自我保护机制，保证不可用服务及时剔除
#    enable-self-preservation: false
#    #剔除间隔时间 （单位ms）
#    eviction-interval-timer-in-ms:  2000
